version: "3.8"

networks:
    nginx-php:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mysql-service
        networks:
            - nginx-php

    # php
    php-service:
        build:
            context: ./php
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: php-container
        ports:
            - "9090:9090"
        volumes:
            - ./app:/var/www/project
            - ./log/php_error.log:/var/log/php_error.log
            - ./mail:/var/mail
        networks:
            - nginx-php

    # mysql
    mysql-service:
        build:
            context: ./mysql
        container_name: mysql-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql8:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - nginx-php

    # node
    node-service:
        build:
            context: ./node
        container_name: node-container
        command: npm start
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php